
name: Java CI with Maven

on:
  push:
    branches:
      #      - '*'         # matches every branch that doesn't contain a '/'
      #      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  #      - '!main'   # excludes main
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -e verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.pullrequest.key=${{github.event.number}} -Dsonar.pullrequest.branch=${{github.head_ref}} -Dsonar.pullrequest.base=${{github.base_ref}} -Dsonar.projectKey=erlin_payments